**Instructions to Follow (Failing to follow these will result mark penalties).**


1.   You can not use any built-in function except len()
2.   You can not use any other python collections except array (e.g: tuptle, dictionaries etc.).
3. We will initialize a new array using numpy library. We have to mention the fixed size during initialization. There might be two approach.

  i. arr = np.array([None] * 10) #Initializing an array length 10 with values None.

  ii. arr = np.array([10, 20, 30, 40]) #Initializing an array length 4 with the values.
4. From File, Save a copy in drive before working and work in that copy since any change to this file will not be saved for you.






In [ ]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [ ]:
# Complete the functions defined in this cell


# Test 01: Play Right
def playRight(sequence,beats):
  n=0
  for i in beats:
    if i==1:
      n+=1
  for j in range(n):
    k=sequence[len(sequence)-1]
    for i in range(len(sequence)-2,-1,-1):
      sequence[i+1]=sequence[i]
    sequence[0]=k

  return sequence


# Test 02: Discard Cards
def discardCards(cards,number):
  count=0
  for i in cards:
    if i==number:
      count+=1

  for j in range(count):
    index=0
    for i in cards:
      if i!=number:
        index+=1
      elif i==number:
        break

    for i in range(index,len(cards)-1):
      cards[i]=cards[i+1]
    cards[len(cards)-1]=0

  return cards


#Test 03: Merge Lineup
def mergeLineup(pokemon_1, pokemon_2):
  j=0
  merge=[]
  for i,char in enumerate(pokemon_1):
    if char==None:
      pokemon_1[i]=0
  for i,char in enumerate(pokemon_2):
    if char==None:
      pokemon_2[i]=0
  while j<len(pokemon_1):
    merge+=[pokemon_1[j]+pokemon_2[len(pokemon_2)-1-j]]
    j+=1
  return np.array(merge)


# Test 04: Balance your Salami
def balanceSalami(salami):
  for n in range(2,len(salami)-1):
    sum1=0
    sum2=0
    l1=[]
    l2=[]
    for i in range(0,n):

      l1+=[salami[i]]
    for j in range(n,len(salami)):
      l2+=[salami[j]]
    for i in l1:
      sum1+=i
    for i in l2:
      sum2+=i
    if sum1==sum2:
      ans=True
      break
    else:
      ans=False
  return ans

# Test 05: Protecc Salami
def protectSalami(salami):
  d={}
  l=[]

  for i in salami:
    if i not in l:
      l+=[i]
  for j in l:
    k=0
    for n in salami:
      if j==n:
        k+=1
    d[j]=k
  for m in d:
    c=0
    for p in d:

        if d[p]==d[m] and d[p]!=1:
            c+=1
        if c>=2:
            ans=True
            return ans
            break

        else:
            ans=False
  return ans


# Test 05: Odd Even Wave
def waveYourFlag(arr):
  for i in range(-1,len(arr)-1):
    if (arr[i-1]%2==0 and arr[i]%2==0 ) or (arr[i-1]%2!=0 and arr[i]%2!=0 ):
      c=arr[i]
      arr[i]=arr[i+1]
      arr[i+1]=c


  return arr






In [ ]:
# This cell is the driver code
# Run this cell after completion of above function.
# You will see the status Accepted after completion if your code is correct.
# If your function is wrong you will see wrong[correction percentage]
# This is called unit testing if you are wondering the checking approach
# No need to write or change any code here. You can only change the inputs

print("///  Test 01: Play Right  ///")
sequence=np.array([10,20,30,40,50,60])
beats = np.array([1,0,0,1,0,1])
returned_value = playRight(sequence, beats)
print(f'Task 1: {returned_value}') # This should print [40, 50, 60, 10, 20, 30]
unittest.output_test(returned_value, np.array([40, 50, 60, 10, 20, 30]))


print("///  Test 02: Discard Cards  ///")
cards = np.array([1,2,3,2,8,2,2,5,7])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1, 3, 8, 5, 7, 0, 0, 0, 0]
unittest.output_test(returned_value, np.array([1, 3, 8, 5, 7, 0, 0, 0, 0]))


print("///  Test 03: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12, 3, 28, -8, 5]))

pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

pokemon_1 = np.array([4, 5, None, None])
pokemon_2 = np.array([2, None, None, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [4,5,0,2]
unittest.output_test(returned_value, np.array([4,5,0,2]))


print("///  Test 04: Balance Your Salami  ///")
salami = np.array([1, 1, 1, 2, 1])
returned_value = balanceSalami(salami)
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = [2, 1, 1, 2, 1]
returned_value = np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print False
unittest.output_test(returned_value, False)

salami = [10, 3, 1, 2, 10]
returned_value =  np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)


print("///  Test 05: Protecc Salami  ///")
salami = np.array([4,5,6,6,4,3,6,4])
returned_value = protectSalami(salami)
print(f'Task 5: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = np.array([3,4,6,3,4,7,4,6,8,6,6])
returned_value = protectSalami(salami)
print(f'Task 5: {returned_value}') # This should print False
unittest.output_test(returned_value, False)


print("///  Test 06: Odd Even Wave  ///")
arr = np.array([2,12,3,8,1,5])
returned_value = waveYourFlag(arr)
print(f'Task 6: {returned_value}') # This should print [2,3,12,1,8,5]
unittest.output_test(returned_value, np.array([2,3,12,1,8,5]))

arr = np.array([45,23,78,84,41])
returned_value = waveYourFlag(arr)
print(f'Task 6: {returned_value}') # This should print [45,78,23,84,41]
unittest.output_test(returned_value, np.array([45,78,23,84,41]))

///  Test 01: Play Right  ///
Task 1: [40 50 60 10 20 30]
Accepted
///  Test 02: Discard Cards  ///
Task 2: [1 3 8 5 7 0 0 0 0]
Accepted
///  Test 03: Merge Lineup  ///
Task 3: [12  3 28 -8  5]
Accepted
Task 3: [ 4 17  6 27  2]
Accepted
Task 3: [4 5 0 2]
Accepted
///  Test 04: Balance Your Salami  ///
Task 4: True
Accepted
Task 4: False
Accepted
Task 4: True
Accepted
///  Test 05: Protecc Salami  ///
Task 5: True
Accepted
Task 5: False
Accepted
///  Test 06: Odd Even Wave  ///
Task 6: [ 5 12  3  8  1  2]
Not Accepted [Your output: [ 5 12  3  8  1  2]  |  Expected Output: [ 2  3 12  1  8  5]]
Task 6: [23 78 45 84 41]
Not Accepted [Your output: [23 78 45 84 41]  |  Expected Output: [45 78 23 84 41]]


In [ ]:
arr=np.array([10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4])

def mean(arr):
  global Mean
  Mean="%f" %float(sum(arr)/len(arr))
  print(f"The mean of the numbers is:{Mean}")
mean(arr)

def standard_deviation(arr):
  global mu
  global stdv
  mu=0
  for i in arr:
    mu+=(i-float(Mean))**2
  stdv=(mu/(len(arr)-1))**0.5
  print(f"The standard deviation is: {stdv}")
standard_deviation(arr)

def num_away_from_mean(arr):
  l=[]
  for i in arr:
    if  abs((i-float(Mean)))>=1.5*stdv:
      l.append(i)
  print(f"New array: {l}")
num_away_from_mean(arr)

[[4.65149753e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 6.75176621e-310 1.50008929e+248]
 [4.31174539e-096 9.80058441e+252 1.23971686e+224]
 [2.59032484e-144 6.06003395e+233 1.06400250e+248]
 [2.59050167e-144 5.22286946e-143 6.32404027e-322]]
